(cl:defpackage mrsd_ros_tutorials-srv
  (:use )
  (:export
   "KINECT_APRILTAG_SR"
   "<KINECT_APRILTAG_SR-REQUEST>"
   "KINECT_APRILTAG_SR-REQUEST"
   "<KINECT_APRILTAG_SR-RESPONSE>"
   "KINECT_APRILTAG_SR-RESPONSE"
   "SAVEDATA"
   "<SAVEDATA-REQUEST>"
   "SAVEDATA-REQUEST"
   "<SAVEDATA-RESPONSE>"
   "SAVEDATA-RESPONSE"
  ))

