// Generated by gencpp from file mrsd_ros_tutorials/kinect_apriltag_sr.msg
// DO NOT EDIT!


#ifndef MRSD_ROS_TUTORIALS_MESSAGE_KINECT_APRILTAG_SR_H
#define MRSD_ROS_TUTORIALS_MESSAGE_KINECT_APRILTAG_SR_H

#include <ros/service_traits.h>


#include <mrsd_ros_tutorials/kinect_apriltag_srRequest.h>
#include <mrsd_ros_tutorials/kinect_apriltag_srResponse.h>


namespace mrsd_ros_tutorials
{

struct kinect_apriltag_sr
{

typedef kinect_apriltag_srRequest Request;
typedef kinect_apriltag_srResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct kinect_apriltag_sr
} // namespace mrsd_ros_tutorials


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::mrsd_ros_tutorials::kinect_apriltag_sr > {
  static const char* value()
  {
    return "505edc86eea6d47b3889e5b914d83993";
  }

  static const char* value(const ::mrsd_ros_tutorials::kinect_apriltag_sr&) { return value(); }
};

template<>
struct DataType< ::mrsd_ros_tutorials::kinect_apriltag_sr > {
  static const char* value()
  {
    return "mrsd_ros_tutorials/kinect_apriltag_sr";
  }

  static const char* value(const ::mrsd_ros_tutorials::kinect_apriltag_sr&) { return value(); }
};


// service_traits::MD5Sum< ::mrsd_ros_tutorials::kinect_apriltag_srRequest> should match 
// service_traits::MD5Sum< ::mrsd_ros_tutorials::kinect_apriltag_sr > 
template<>
struct MD5Sum< ::mrsd_ros_tutorials::kinect_apriltag_srRequest>
{
  static const char* value()
  {
    return MD5Sum< ::mrsd_ros_tutorials::kinect_apriltag_sr >::value();
  }
  static const char* value(const ::mrsd_ros_tutorials::kinect_apriltag_srRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::mrsd_ros_tutorials::kinect_apriltag_srRequest> should match 
// service_traits::DataType< ::mrsd_ros_tutorials::kinect_apriltag_sr > 
template<>
struct DataType< ::mrsd_ros_tutorials::kinect_apriltag_srRequest>
{
  static const char* value()
  {
    return DataType< ::mrsd_ros_tutorials::kinect_apriltag_sr >::value();
  }
  static const char* value(const ::mrsd_ros_tutorials::kinect_apriltag_srRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::mrsd_ros_tutorials::kinect_apriltag_srResponse> should match 
// service_traits::MD5Sum< ::mrsd_ros_tutorials::kinect_apriltag_sr > 
template<>
struct MD5Sum< ::mrsd_ros_tutorials::kinect_apriltag_srResponse>
{
  static const char* value()
  {
    return MD5Sum< ::mrsd_ros_tutorials::kinect_apriltag_sr >::value();
  }
  static const char* value(const ::mrsd_ros_tutorials::kinect_apriltag_srResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::mrsd_ros_tutorials::kinect_apriltag_srResponse> should match 
// service_traits::DataType< ::mrsd_ros_tutorials::kinect_apriltag_sr > 
template<>
struct DataType< ::mrsd_ros_tutorials::kinect_apriltag_srResponse>
{
  static const char* value()
  {
    return DataType< ::mrsd_ros_tutorials::kinect_apriltag_sr >::value();
  }
  static const char* value(const ::mrsd_ros_tutorials::kinect_apriltag_srResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // MRSD_ROS_TUTORIALS_MESSAGE_KINECT_APRILTAG_SR_H
