// Generated by gencpp from file mrsd_ros_tutorials/SaveData.msg
// DO NOT EDIT!


#ifndef MRSD_ROS_TUTORIALS_MESSAGE_SAVEDATA_H
#define MRSD_ROS_TUTORIALS_MESSAGE_SAVEDATA_H

#include <ros/service_traits.h>


#include <mrsd_ros_tutorials/SaveDataRequest.h>
#include <mrsd_ros_tutorials/SaveDataResponse.h>


namespace mrsd_ros_tutorials
{

struct SaveData
{

typedef SaveDataRequest Request;
typedef SaveDataResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct SaveData
} // namespace mrsd_ros_tutorials


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::mrsd_ros_tutorials::SaveData > {
  static const char* value()
  {
    return "505edc86eea6d47b3889e5b914d83993";
  }

  static const char* value(const ::mrsd_ros_tutorials::SaveData&) { return value(); }
};

template<>
struct DataType< ::mrsd_ros_tutorials::SaveData > {
  static const char* value()
  {
    return "mrsd_ros_tutorials/SaveData";
  }

  static const char* value(const ::mrsd_ros_tutorials::SaveData&) { return value(); }
};


// service_traits::MD5Sum< ::mrsd_ros_tutorials::SaveDataRequest> should match 
// service_traits::MD5Sum< ::mrsd_ros_tutorials::SaveData > 
template<>
struct MD5Sum< ::mrsd_ros_tutorials::SaveDataRequest>
{
  static const char* value()
  {
    return MD5Sum< ::mrsd_ros_tutorials::SaveData >::value();
  }
  static const char* value(const ::mrsd_ros_tutorials::SaveDataRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::mrsd_ros_tutorials::SaveDataRequest> should match 
// service_traits::DataType< ::mrsd_ros_tutorials::SaveData > 
template<>
struct DataType< ::mrsd_ros_tutorials::SaveDataRequest>
{
  static const char* value()
  {
    return DataType< ::mrsd_ros_tutorials::SaveData >::value();
  }
  static const char* value(const ::mrsd_ros_tutorials::SaveDataRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::mrsd_ros_tutorials::SaveDataResponse> should match 
// service_traits::MD5Sum< ::mrsd_ros_tutorials::SaveData > 
template<>
struct MD5Sum< ::mrsd_ros_tutorials::SaveDataResponse>
{
  static const char* value()
  {
    return MD5Sum< ::mrsd_ros_tutorials::SaveData >::value();
  }
  static const char* value(const ::mrsd_ros_tutorials::SaveDataResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::mrsd_ros_tutorials::SaveDataResponse> should match 
// service_traits::DataType< ::mrsd_ros_tutorials::SaveData > 
template<>
struct DataType< ::mrsd_ros_tutorials::SaveDataResponse>
{
  static const char* value()
  {
    return DataType< ::mrsd_ros_tutorials::SaveData >::value();
  }
  static const char* value(const ::mrsd_ros_tutorials::SaveDataResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // MRSD_ROS_TUTORIALS_MESSAGE_SAVEDATA_H
