// Generated by gencpp from file mrsd_ros_tutorials/SaveDataResponse.msg
// DO NOT EDIT!


#ifndef MRSD_ROS_TUTORIALS_MESSAGE_SAVEDATARESPONSE_H
#define MRSD_ROS_TUTORIALS_MESSAGE_SAVEDATARESPONSE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace mrsd_ros_tutorials
{
template <class ContainerAllocator>
struct SaveDataResponse_
{
  typedef SaveDataResponse_<ContainerAllocator> Type;

  SaveDataResponse_()
    : status(0)  {
    }
  SaveDataResponse_(const ContainerAllocator& _alloc)
    : status(0)  {
  (void)_alloc;
    }



   typedef uint64_t _status_type;
  _status_type status;




  typedef boost::shared_ptr< ::mrsd_ros_tutorials::SaveDataResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::mrsd_ros_tutorials::SaveDataResponse_<ContainerAllocator> const> ConstPtr;

}; // struct SaveDataResponse_

typedef ::mrsd_ros_tutorials::SaveDataResponse_<std::allocator<void> > SaveDataResponse;

typedef boost::shared_ptr< ::mrsd_ros_tutorials::SaveDataResponse > SaveDataResponsePtr;
typedef boost::shared_ptr< ::mrsd_ros_tutorials::SaveDataResponse const> SaveDataResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::mrsd_ros_tutorials::SaveDataResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::mrsd_ros_tutorials::SaveDataResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace mrsd_ros_tutorials

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/opt/ros/indigo/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::mrsd_ros_tutorials::SaveDataResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::mrsd_ros_tutorials::SaveDataResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::mrsd_ros_tutorials::SaveDataResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::mrsd_ros_tutorials::SaveDataResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::mrsd_ros_tutorials::SaveDataResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::mrsd_ros_tutorials::SaveDataResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::mrsd_ros_tutorials::SaveDataResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "6f65b1a6d007112dd65cefd670e94e47";
  }

  static const char* value(const ::mrsd_ros_tutorials::SaveDataResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x6f65b1a6d007112dULL;
  static const uint64_t static_value2 = 0xd65cefd670e94e47ULL;
};

template<class ContainerAllocator>
struct DataType< ::mrsd_ros_tutorials::SaveDataResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "mrsd_ros_tutorials/SaveDataResponse";
  }

  static const char* value(const ::mrsd_ros_tutorials::SaveDataResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::mrsd_ros_tutorials::SaveDataResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "uint64 status\n\
\n\
";
  }

  static const char* value(const ::mrsd_ros_tutorials::SaveDataResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::mrsd_ros_tutorials::SaveDataResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.status);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct SaveDataResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::mrsd_ros_tutorials::SaveDataResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::mrsd_ros_tutorials::SaveDataResponse_<ContainerAllocator>& v)
  {
    s << indent << "status: ";
    Printer<uint64_t>::stream(s, indent + "  ", v.status);
  }
};

} // namespace message_operations
} // namespace ros

#endif // MRSD_ROS_TUTORIALS_MESSAGE_SAVEDATARESPONSE_H
